# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 10
    reviewers:
      - "reviewer1"
      - "reviewer2"
    assignees:
      - "assignee1"
    labels:
      - "dependencies"
      - "security"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
    open-pull-requests-limit: 10
    reviewers:
      - "reviewer1"
    assignees:
      - "assignee1"
    labels:
      - "dependencies"
      - "security"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5
    reviewers:
      - "reviewer1"
    assignees:
      - "assignee1"
    labels:
      - "dependencies"
      - "ci"
